# Generated by Django 3.1.7 on 2021-03-06 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mark',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='AHW0', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='HW0', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='UV0', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 19, 40, 832749), verbose_name='Time submited'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timeuploded',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 19, 19, 40, 832474)),
        ),
    ]
