# Generated by Django 3.1.7 on 2021-03-06 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210306_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pdffile',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 23, 23, 14, 472863), verbose_name='Time submited'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timeuploded',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 23, 23, 14, 472514)),
        ),
    ]
