# Generated by Django 3.1.7 on 2021-03-07 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210306_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdffile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 8, 47, 0, 36544, tzinfo=utc), verbose_name='Time submited'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timeuploded',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 8, 47, 0, 36202, tzinfo=utc)),
        ),
    ]
