# Generated by Django 3.1.7 on 2021-03-07 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210307_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='video',
            name='vfile',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 17, 24, 9, 772827), verbose_name='Time submited'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timeuploded',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 17, 24, 9, 772475)),
        ),
    ]
