# Generated by Django 3.1.7 on 2021-03-07 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210307_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 20, 21, 53, 692241), verbose_name='Time submited'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timeuploded',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 20, 21, 53, 691968)),
        ),
    ]
